### PR TITLE
Update Guzzle version to match Magento 2.4.4 & PHP 8.1

### PR DESCRIPTION
**Pull request by JustinElst**
Magento 2.4.4 requires Guzzle 7.3, so its updated.
I do need to test this though, the pull-request is here only to save you a bit of time.

### CODE REVIEW

**Comment by evs-xsarus** [comment]
@MrGekko on PHP 8.1, this error is given:

>  Deprecated Functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php on line 66

Fix:

```diff
--- dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php
+++ dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php
@@ -63,7 +63,7 @@
     {
         $pattern = trim($pattern);
         $pattern = '/' . trim($pattern, '/') . '/';
-        if (preg_match($pattern, null) === false) {
+        if (preg_match($pattern, '') === false) {
             throw new \InvalidArgumentException("Regex pattern '{$pattern}' does not appear to be valid");
         }
 

```

**Comment by peterjaap** [comment]
LGTM!

**Comment by JustinElst** [comment]
Thanks for checking, committed the patch mantioned by @evs-xsarus.
I test-run the command and did not get any errors.
Success is: 1, with service Vies
Success is: 1, with service Vatlayer
Success is: 1, with service RegExp

**Comment by evs-xsarus** [comment]
@MrGekko found this during testing:

```
[2022-05-25T11:38:59.905869+00:00] report.ERROR: Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /sites/dlk_upgrade/current/magento/vendor/dutchento/m2-vatfallback/Service/CleanNumberString.php on line 26#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8192, 'preg_replace():...', '/sites/dlk_upgr...', 26)
#1 /sites/dlk_upgrade/current/magento/vendor/dutchento/m2-vatfallback/Service/CleanNumberString.php(26): preg_replace(Array, '', NULL)
#2 /sites/dlk_upgrade/current/magento/vendor/dutchento/m2-vatfallback/Plugin/Magento/Customer/Model/Vat.php(69): Dutchento\Vatfallback\Service\CleanNumberString->returnStrippedString(NULL)
#3 /sites/dlk_upgrade/current/magento/vendor/magento/framework/Interception/Interceptor.php(135): Dutchento\Vatfallback\Plugin\Magento\Customer\Model\Vat->aroundCheckVatNumber(Object(Magento\Customer\Model\Vat\Interceptor), Object(Closure), 'NL', NULL)
```

Fix:

```diff
--- vendor/dutchento/m2-vatfallback/Service/CleanNumberString.php
+++ vendor/dutchento/m2-vatfallback/Service/CleanNumberString.php
@@ -28,7 +28,7 @@
                 '/[^0-9a-z]+/i'
             ],
             '',
-            $vatInput
+            $vatInput ?? ''
         );
     }
 }
```

**Comment by JustinElst** [comment]
@evs-xsarus Thanks added the fix. What php version are you on?

**Comment by evs-xsarus** [comment]
@MrGekko I'm running

```
PHP 8.1.1 (cli) (built: Dec 21 2021 19:46:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by JustinElst** [comment]
Thanks, im still @ 7.4 so thanks for your testing! Much appreciated.

**Comment by JeroenBoersma** [comment]
LGTM, @peterjaap or @sandermangel please merge

**Comment by peterjaap** [comment]
Done https://github.com/Dutchento/m2-vatfallback/releases/tag/1.7.0

**Pull request merged**
